# Jenkins LTS + JDK17 베이스
FROM jenkins/jenkins:lts-jdk17

USER root

# docker CLI 설치
RUN apt-get update && \
    apt-get install -y docker.io && \
    apt-get clean

# 다시 jenkins 사용자로 변경
USER jenkins

